
MENU_HEIGHT = 75
MENU_WIDTH = 150
MENU_BUFFER = 20
DEFAULT_X = 10
DEFAULT_Y = 10
CORNER_SCALING = 0.5

-- Child Positions
POSITION_TOP = 1
POSITION_LEFT = 2
POSITION_BOTTOM = 3
POSITION_RIGHT = 4

-- Note Constants
NOTE_MAX_RADIUS = 40
NOTE_MIN_RADIUS = 25
NOTE_SCALE_FACTOR = 8
NOTE_A = "A"
NOTE_B = "B"
NOTE_C = "C"
NOTE_D = "D"
NOTE_E = "E"
NOTE_F = "F"
NOTE_G = "G"
NOTE_SHARP = "#"
NOTE_FLAT = "b"
